New vaccination logic
mild-blue/covid-vaxx pull request #182
Opened 2021-03-19 13:58 UTC by misslecter

Closes #169

2021-03-30 08:01 UTC, LukasForst commented
1. po kliku na "registrovat dalsi osobu" je formular s otazka vyplneny s daty predchozi osoby
![image](https://user-images.githubusercontent.com/14038818/112952784-2aadd500-913d-11eb-8722-0f65bd147b93.png)

2. printime do console sestricky, na kod jsem nekoukal, ale pokud pouzivame tu log service, tak by se to pri produkcnim buildu dit nemelo, je to tak?
![image](https://user-images.githubusercontent.com/14038818/112953069-71033400-913d-11eb-9965-425724be4463.png)

3. zmenit datum vakcinace zatim backend neumi, je to kvuli tomu, ze se ty entity museli roztrhnout a zabralo by to dalsi netrivialni praci, takze jsem to radsi zahodil, tudiz je treba tohle policko neumoznit zatim editovat (mozna to do budoucna pridame na BE taky, tzn kod si nekde klidne nechat za feature flagem)
![image](https://user-images.githubusercontent.com/14038818/112953754-06062d00-913e-11eb-933c-d5cec0578043.png)

4. obecne mame trochu problem s tou validaci telefonnich cisel, jak psal @tomaskourim v #44 tak BE je vyrazne striktnejsi v tom, co je validni a co ne. Nejsem si ale jistej, jake je idealni reseni tbh, bud na FE nahodit taky nejakou tu googli knihovnu (ackoliv jsem si myslel, ze uz tu je), anebo ji na BE smazat, protoze soucasny stav je trochu pitomej --- nicmene tohle pojdme vyresit v jinem PR k #44 
![image](https://user-images.githubusercontent.com/14038818/112953976-3ea60680-913e-11eb-93e1-4a409b373806.png)
```
message: "Bad request: Parameter phoneNumber = (DE) 701123456 is not valid.."
```

5. kdyz nebyla indikace a ja ji chci zmenit, tak mi to nedovoli ulozit 
![image](https://user-images.githubusercontent.com/14038818/112954355-9c3a5300-913e-11eb-8995-198010c8c738.png)

6. navic kdyz uz ji zmenim a zmenim i neco dalsiho, tak se indikace stejne neulozi
![image](https://user-images.githubusercontent.com/14038818/112954518-becc6c00-913e-11eb-83ae-e6f69ae6a3ca.png)
![image](https://user-images.githubusercontent.com/14038818/112954543-c4c24d00-913e-11eb-84e2-e00a993ad379.png)

2021-03-30 08:01 UTC, LukasForst requested changes
viz predchozi comment

2021-04-05 15:10 UTC, misslecter commented
@LukasForst koukám, že mi na BE chybí u `PUT ​/api​/admin​/patient​/{id}` parameter `indication`. Zbytek připomínek jsou done

2021-04-06 16:15 UTC, LukasForst commented
@misslecter prihodil jsem support na BE, ted uz by to mohlo zacit fungovat?

2021-04-07 17:34 UTC, LukasForst approved these changes

2021-04-07 17:34 UTC, merged