Implement a fix in DataCorrectnessRoutesTest #255 and updated the backend README
mild-blue/covid-vaxx pull request #387
Opened 2022-07-21 00:03 UTC by peterstran

2022-07-27 09:09 UTC, tomaskourim requested changes

2022-07-27 09:09 UTC, tomaskourim commented on backend/src/test/kotlin/blue/mild/covid/vaxx/routes/DataCorrectnessRoutesTest.kt
> +
you can remove the TODO and the instructions part of the text, just leave the description

2022-07-27 09:09 UTC, tomaskourim commented on backend/src/test/kotlin/blue/mild/covid/vaxx/routes/DataCorrectnessRoutesTest.kt
> +        handleRequest( HttpMethod.Get, "${Routes.dataCorrectness}?id=${patient1.id}" ) {
use some autoformat (Idea has it built in, Ctrl+Alt+L) to remove extra spaces and insert the missing ones

2022-07-27 09:09 UTC, tomaskourim commented on backend/src/test/kotlin/blue/mild/covid/vaxx/routes/DataCorrectnessRoutesTest.kt
> +            print(assertEquals(correctnessId,output.id))
why do you need to print it?

2022-08-09 11:46 UTC, tomaskourim approved these changes

2022-08-11 12:44 UTC, LukasForst commented
@peterstran feel free to merge

* closes #255

2022-08-11 13:35 UTC, merged